import type { Customer, DeliveryRule, KnowledgeEntry, Order, Product } from "./types";

export const notionDatabase = {
  title: "Demo Fruit Shop 知識庫",
  databaseId: "00000000000000000000000000000000",
  dataSourceId: "00000000-0000-0000-0000-000000000000",
  viewId: "00000000000000000000000000000000",
  syncedAt: "2026-01-01 00:00",
};

export const products: Product[] = [
  {
    id: "banana-box",
    name: "香蕉（進口菲律賓）",
    category: "當季水果",
    description: "色澤較綠，適合需放幾天的學校、公司與餐飲客戶。",
    spec: "進口菲律賓，箱(13kg)",
    unit: "箱",
    price: 460,
    stockStatus: "有貨",
    imageUrl:
      "https://images.unsplash.com/photo-1528825871115-3581a5387919?auto=format&fit=crop&w=900&q=80",
    sortOrder: 1,
    notionTitle: "香蕉（進口菲律賓）",
    notionContent: "規格 進口菲律賓；單位 箱(13kg)；參考價 460 元；供應中；色澤較綠，適合需放幾天的客戶。",
    sourceStatus: "啟用",
    freshnessNote: "需放熟 2-3 天",
  },
  {
    id: "mango-box",
    name: "芒果",
    category: "當季水果",
    description: "國產愛文，香氣足，適合活動餐盒與節慶贈禮。",
    spec: "國產愛文，箱(5kg)",
    unit: "箱",
    price: 650,
    stockStatus: "少量",
    imageUrl:
      "https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?auto=format&fit=crop&w=900&q=80",
    sortOrder: 2,
    notionTitle: "芒果",
    notionContent: "規格 國產愛文；單位 箱(5kg)；參考價 650 元；季節限定5月至7月。",
    sourceStatus: "啟用",
    freshnessNote: "5-7 月季節限定",
  },
  {
    id: "pineapple-box",
    name: "鳳梨",
    category: "當季水果",
    description: "國產金鑽17號，甜度穩定，可免費削皮代工。",
    spec: "國產金鑽17號，箱(10kg)",
    unit: "箱",
    price: 380,
    stockStatus: "有貨",
    imageUrl:
      "https://images.unsplash.com/photo-1550258987-190a2d41a8ba?auto=format&fit=crop&w=900&q=80",
    sortOrder: 3,
    notionTitle: "鳳梨",
    notionContent: "規格 國產金鑽17號；單位 箱(10kg)；參考價 380 元；供應中；可免費削皮代工，需提前告知。",
    sourceStatus: "啟用",
    freshnessNote: "削皮需提前告知",
  },
  {
    id: "lemon-kg",
    name: "檸檬",
    category: "進口水果",
    description: "屏東無籽，飲品店與早餐店常備，大量訂購可議價。",
    spec: "國產屏東無籽，公斤",
    unit: "公斤",
    price: 75,
    stockStatus: "有貨",
    imageUrl:
      "https://images.unsplash.com/photo-1590502593747-42a996133562?auto=format&fit=crop&w=900&q=80",
    sortOrder: 4,
    notionTitle: "檸檬",
    notionContent: "規格 國產屏東無籽；單位 公斤；參考價 75 元；供應中；大量訂購可議價。",
    sourceStatus: "啟用",
    freshnessNote: "飲品店常備",
  },
  {
    id: "strawberry-box",
    name: "草莓",
    category: "禮盒組合",
    description: "國產大湖特級，易損需冷藏配送，適合午茶與禮盒。",
    spec: "大湖特級，盒(400g)",
    unit: "盒",
    price: 180,
    stockStatus: "預購",
    imageUrl:
      "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?auto=format&fit=crop&w=900&q=80",
    sortOrder: 5,
    notionTitle: "草莓",
    notionContent: "規格 國產大湖特級；單位 盒(400g)；參考價 180 元；季節限定12月至隔年3月，易損需冷藏配送。",
    sourceStatus: "啟用",
    freshnessNote: "12-3 月冷藏配送",
  },
  {
    id: "apple-case",
    name: "青森蘋果",
    category: "學校團膳",
    description: "清脆耐放，適合固定配送、學校點心與公司茶水間。",
    spec: "進口青森，箱",
    unit: "箱",
    price: 1280,
    stockStatus: "有貨",
    imageUrl:
      "https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?auto=format&fit=crop&w=900&q=80",
    sortOrder: 6,
    notionTitle: "青森蘋果",
    notionContent: "青森蘋果固定配送商品資料。",
    sourceStatus: "啟用",
    freshnessNote: "固定配送推薦",
  },
];

export const knowledgeEntries: KnowledgeEntry[] = [
  {
    id: "order-minimum",
    title: "最低訂購量",
    category: "FAQ訂購",
    status: "啟用",
    content: "散客可少量訂購；台中市區學校、公司與餐飲固定配送滿 2,000 元免運，周邊區域依配送規則計算。",
  },
  {
    id: "delivery-time",
    title: "配送時間",
    category: "FAQ配送",
    status: "啟用",
    content: "當日下午三點前確認的訂單隔日上午送達；生鮮易損品採冷藏宅配。",
  },
  {
    id: "payment",
    title: "付款方式",
    category: "FAQ付款",
    status: "啟用",
    content: "支援現場付款、匯款與固定合作客戶月結；月結客戶需留統編與聯絡窗口。",
  },
  {
    id: "returns",
    title: "退換貨",
    category: "FAQ退換貨",
    status: "啟用",
    content: "到貨 24 小時內若有品質問題，請拍照透過 LINE 回報，確認後免費補貨或退款。",
  },
];

export const mockCustomer: Customer = {
  name: "示範國小",
  lineUserId: "mock-line-user",
  type: "學校",
  contactPerson: "王主任",
  phone: "0900-000-000",
  address: "示範市示範區示範路一段 1 號",
  taxId: "00000000",
  favoriteProducts: "香蕉、鳳梨、青森蘋果、學校團膳水果包",
  notes: "週三上午配送，請送至總務處旁收貨口。",
};

export const deliveryRules: DeliveryRule[] = [
  {
    id: "taichung-core",
    name: "台中市區配送",
    area: "台中市區",
    districts: ["中區", "東區", "南區", "西區", "北區", "北屯區", "西屯區", "南屯區", "太平區", "大里區"],
    freeShippingThreshold: 2000,
    deliveryFee: 150,
    minOrderAmount: 1000,
    isActive: true,
    notes: "主要配送範圍，滿 2,000 免運；未滿酌收 150 元配送費。",
    sortOrder: 1,
  },
  {
    id: "taichung-ring",
    name: "屯區配送",
    area: "屯區",
    districts: ["潭子區", "大雅區", "神岡區", "豐原區", "烏日區", "霧峰區"],
    freeShippingThreshold: 3000,
    deliveryFee: 200,
    minOrderAmount: 1500,
    isActive: true,
    notes: "台中周邊固定客戶配送區，滿 3,000 免運。",
    sortOrder: 2,
  },
  {
    id: "taichung-coast",
    name: "海線配送",
    area: "海線",
    districts: ["沙鹿區", "龍井區", "大肚區", "梧棲區", "清水區", "大甲區", "外埔區", "大安區"],
    freeShippingThreshold: 5000,
    deliveryFee: 300,
    minOrderAmount: 2500,
    isActive: true,
    notes: "海線需提前一天確認配送量與車趟，滿 5,000 免運。",
    sortOrder: 3,
  },
  {
    id: "taichung-mountain",
    name: "山線配送",
    area: "山線",
    districts: ["后里區", "石岡區", "東勢區", "新社區", "和平區"],
    freeShippingThreshold: 6000,
    deliveryFee: 400,
    minOrderAmount: 3000,
    isActive: true,
    notes: "山線與較遠區域需先確認配送時間，滿 6,000 免運。",
    sortOrder: 4,
  },
  {
    id: "out-of-area",
    name: "外縣市暫不配送",
    area: "外縣市",
    districts: ["彰化", "南投", "苗栗", "其他縣市"],
    freeShippingThreshold: 0,
    deliveryFee: 0,
    minOrderAmount: 0,
    isActive: false,
    notes: "第一版先不開放外縣市配送，可由人工客服另行確認。",
    sortOrder: 99,
  },
];

export const seedOrders: Order[] = [
  {
    orderId: "FG20260627001",
    customerName: "示範國小",
    lineUserId: "mock-line-user",
    status: "配送中",
    items: [
      {
        productId: "banana-box",
        name: "台灣香蕉",
        spec: "1箱，約18-20根",
        unit: "箱",
        price: 420,
        quantity: 3,
      },
      {
        productId: "pineapple-box",
        name: "鳳梨",
        spec: "國產金鑽17號，箱(10kg)",
        unit: "箱",
        price: 380,
        quantity: 2,
      },
    ],
    subtotal: 2140,
    deliveryFee: 0,
    totalAmount: 2140,
    paymentMethod: "月結",
    receiverName: "林主任",
    phone: "04-2345-6789",
    deliveryAddress: "台中市北區示範路一段 1 號",
    deliveryDate: "2026-06-28",
    deliveryTimeSlot: "上午",
    notes: "送至總務處。",
    createdAt: "2026-06-27T09:20:00.000+08:00",
    updatedAt: "2026-06-27T09:30:00.000+08:00",
  },
];

export const categories = [
  "全部",
  "當季水果",
  "進口水果",
  "禮盒組合",
  "學校團膳",
  "公司訂購",
] as const;
